services:
  - type: web
    name: your-service-name
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    plan: free
    runtime: python
    version: 3.12.3
