services:
  - type: web
    name: solana-sniper-bot
    runtime: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: PIP_NO_CACHE_DIR
        value: "false"
      - key: MIN_LIQUIDITY_LAMPORTS
        value: "20000000000"
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: RPC_URL
        sync: false
      - key: PRIVATE_KEY
        sync: false
      - key: BUY_AMOUNT_SOL
        value: "0.05"
      - key: PROFIT_TARGET
        value: "2.0"
      - key: STOP_LOSS
        value: "0.5"
