services:
  - type: web
    name: telegram-sniper-bot
    env: python
    runtime: python
    version: 3.12.3
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
